### ISSUE TITLE
New Api integration

### ISSUE THREAD

**Issue by ashovdra** [eoko/magento2-client#1]
Hi

What is the correct way to implement and integrate new Api, like existing ProductApi

Thanks

**Comment by merlindorin** [comment]
hi,
It's not that complicated, every endpoints use a custom interface `src/Api/ProductApiInterface.php` that implement operation `src/Api/Operation`. You can find an example of implementation in `src/Api/ProductApi.php`. Each endpoint is plugged in the client constructor `src/MagentoClient.php` or through the ClientBuilder `src/MagentoClientBuilder.php`.

The idea behind `src/Api/ProductApi.php` is to have reusable object that can work without a complex tree object. Each endpoint require a `ResourceClientInterface`, a `PageInterface` and a `CursorFactory`... nothing more.

To be honest, I'm not a big fan of the Magento API (quite dirty... for example, a missing query param without value (CriteriaParam) put the request in error :/). that's why we only implement what we need for our current customer.

If you are motivated to implement new end point, don't hesitate to make a PR, I'l will review it even if we have no particularly needs ;)

**Comment by merlindorin** [comment]
Close due to inactivity
